name: 友链申请
title: "友链申请"
description: "申请添加友链到Snowykami的主页"
labels: ["friend-link"]
body:
  - type: input
    id: name
    attributes:
      label: 名称
      description: 网站的名称
      placeholder: "例如: 李田所的博客"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 描述
      description: 网站的描述
      placeholder: "例如: 李田所的个人博客，记录了他的学习和生活"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: 链接
      description: 网站的链接
      placeholder: "例如: https://lts.blog"
    validations:
      required: true

  - type: input
    id: avatar
    attributes:
      label: 头像链接
      description: 网站的头像链接
      placeholder: "例如: https://lts.blog/avatar.png"
    validations:
      required: true

  - type: checkboxes
    id: recheck
    attributes:
      label: 重新检查
      description: 如需重新检查请勾选
      options:
        - label: 我同意遵循该项目的行为准则
          required: true
