
name: 部署页面

on:
  push:
    branches:
      - main

permissions:
  contents: write
  statuses: write

env:
  MELI_SITE: 5962f229-1e15-46cd-9b18-1f04035efb61

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 8


      - name: setup Node.js
        run: |-
          pnpm install

      - name: build page
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run build
          > dist/.nojekyll


      - name: "发布"
        run: |
          npx -p "@getmeli/cli" meli upload ./dist \
            --url "https://meli.liteyuki.icu" \
            --site "$MELI_SITE" \
            --token "$MELI_TOKEN" \
            --release "$GITHUB_SHA"
        env:
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}