name: Process Friend Link Request

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  process-friend-link:
    if: contains(github.event.issue.labels.*.name, 'friend-link')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Run Python script
        run: |
          uv run ./scripts/issue_handler