name: Handle Friend Link Request

on:
  issues:
    types: [opened, edited, labeled]

concurrency:
  group: has-git-operations
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  handle-friend-link:
    if: contains(github.event.issue.labels.*.name, 'friend-link')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Run Python script
        run: |
          uv run ./scripts/issue_handler
        env: 
          GITHUB_EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}