name: Handle Friend Link Request

on:
  issues:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created, edited]

concurrency:
  group: has-git-operations
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  handle-friend-link:
    if: contains(github.event.issue.labels.*.name, 'friend-link')
    runs-on: ubuntu-latest
    container:
      image: playwright/chromium
    steps:
      - name: Install node
        run: |
          apt-get install -y nodejs npm

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install playwright and run Python script
        run: |
          uv run ./scripts/issue_handler
        env: 
          GITHUB_EVENT_COMMENT_ID: ${{ github.event.comment.id }}
          GITHUB_EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}  # 
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.LITEYUKI_FLOW_TOKEN }}
          FRIEND_LINKS_FILE: data/friends.json
          I18N_FILE: data/i18n.json

          AI_API_ENDPOINT: "https://models.github.ai/inference/chat/completions"
          AI_API_KEY: ${{ secrets.LITEYUKI_FLOW_TOKEN }}
          AI_MODEL: "openai/gpt-4.1-nano"